use parkingproject;

insert into Location (ShortName, Address) values ('ALFRE', '71 Continental Alley');
insert into Location (ShortName, Address) values ('NIKOL', '048 Welch Junction');
insert into Location (ShortName, Address) values ('FILMO', '5 Ilene Junction');
insert into Location (ShortName, Address) values ('MORDE', '9004 Packers Lane');
insert into Location (ShortName, Address) values ('CHICK', '2 Northridge Drive');
insert into Location (ShortName, Address) values ('OBIDI', '6576 Mcbride Street');
insert into Location (ShortName, Address) values ('LESLI', '378 Beilfuss Junction');
insert into Location (ShortName, Address) values ('EZRAL', '81122 Barnett Trail');
insert into Location (ShortName, Address) values ('FELIC', '869 Jana Way');
insert into Location (ShortName, Address) values ('DOMEN', '185 Buena Vista Lane');
insert into Location (ShortName, Address) values ('BARNY', '4 Leroy Street');
insert into Location (ShortName, Address) values ('DOMEH', '1 Ridgeview Hill');
insert into Location (ShortName, Address) values ('KARIM', '0 Norway Maple Junction');
insert into Location (ShortName, Address) values ('TYNAN', '1 Welch Alley');
insert into Location (ShortName, Address) values ('PATRI', '13 Holy Cross Center');
insert into Location (ShortName, Address) values ('ANYYY', '50224 Leroy Place');
insert into Location (ShortName, Address) values ('ALFON', '5 Menomonie Crossing');
insert into Location (ShortName, Address) values ('WENDE', '2049 Miller Crossing');
insert into Location (ShortName, Address) values ('GIORD', '1 Marcy Crossing');
insert into Location (ShortName, Address) values ('HERCU', '41376 Johnson Park');
insert into Location (ShortName, Address) values ('ROYAL', '32 Rockefeller Center');
insert into Location (ShortName, Address) values ('SAYER', '537 Farwell Circle');
insert into Location (ShortName, Address) values ('ROMAW', '5006 Fairview Avenue');
insert into Location (ShortName, Address) values ('YANAT', '735 Namekagon Point');
insert into Location (ShortName, Address) values ('LAMMO', '2799 Hovde Avenue');
insert into Location (ShortName, Address) values ('VINCE', '811 Maywood Crossing');
insert into Location (ShortName, Address) values ('TEODO', '779 Carpenter Park');
insert into Location (ShortName, Address) values ('RONAL', '9989 Graedel Pass');
insert into Location (ShortName, Address) values ('EFREN', '94901 Dorton Alley');
insert into Location (ShortName, Address) values ('WILBE', '658 Hansons Crossing');
insert into Location (ShortName, Address) values ('FALKN', '08530 Rutledge Parkway');
insert into Location (ShortName, Address) values ('JAMIL', '29338 Amoth Avenue');
insert into Location (ShortName, Address) values ('EDSEL', '73 Cody Crossing');
insert into Location (ShortName, Address) values ('RICKI', '8 Autumn Leaf Parkway');
insert into Location (ShortName, Address) values ('GIANN', '69340 Claremont Drive');
insert into Location (ShortName, Address) values ('SAMNM', '689 Express Park');
insert into Location (ShortName, Address) values ('WERNH', '75118 Clove Drive');
insert into Location (ShortName, Address) values ('DEWOO', '166 Hooker Plaza');
insert into Location (ShortName, Address) values ('LOUEE', '03787 Stoughton Junction');
insert into Location (ShortName, Address) values ('BRANQ', '308 Bluejay Court');
insert into Location (ShortName, Address) values ('HEWEW', '725 Rieder Park');
insert into Location (ShortName, Address) values ('IKELE', '8614 Hayes Way');
insert into Location (ShortName, Address) values ('WESTO', '0 Luster Circle');
insert into Location (ShortName, Address) values ('KILEE', '805 Evergreen Place');
insert into Location (ShortName, Address) values ('KANEE', '9 Mcguire Lane');
insert into Location (ShortName, Address) values ('ZEBED', '1300 John Wall Road');
insert into Location (ShortName, Address) values ('TYMON', '9701 Orin Hill');
insert into Location (ShortName, Address) values ('RAVIV', '34 Dahle Point');
insert into Location (ShortName, Address) values ('RUDOL', '71 Sutteridge Junction');
insert into Location (ShortName, Address) values ('PADGE', '61 Basil Junction');


insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Stanislaus Tomblett', 'stomblett0@springer.com', '83KdcV', '+48 471 149 8281', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Evonne Garriock', 'egarriock1@examiner.com', 'SoIucdam73SR', '+55 624 211 7225', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Anabal Chong', 'achong2@psu.edu', 'y5JhDz4b', '+86 723 517 4857', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Tye Whitcher', 'twhitcher3@jimdo.com', 'TDsDKtLqQG9v', '+7 359 675 8810', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Salli Sired', 'ssired4@gizmodo.com', '47cHUE09N3lw', '+57 806 594 3103', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Hill Salzberger', 'hsalzberger5@state.gov', 'UvU9fnHA', '+1 318 662 8902', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Mab Randals', 'mrandals6@purevolume.com', 'j6aQtltk', '+86 208 897 6041', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Sunny Halliday', 'shalliday7@answers.com', 'uo1ZvddMI', '+351 162 419 8491', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Jenna Schultze', 'jschultze8@storify.com', 'wrpmgi3wIX5u', '+86 748 994 9241', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Griffin Knevet', 'gknevet9@livejournal.com', 'PS9ZdyvX', '+1 752 248 0987', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Avivah Stannering', 'astanneringa@yelp.com', 'JT9rlA', '+86 917 775 5439', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Jeffie Overton', 'jovertonb@digg.com', '6P4pw7gY3', '+46 343 613 0926', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Minnie Clift', 'mcliftc@apple.com', 'tMYzHa5', '+62 285 315 1010', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Skell Quennell', 'squennelld@dedecms.com', '2uMCZq4BAiT', '+267 566 564 0100', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Jerrome Wey', 'jweye@gravatar.com', 'jH3w38lOVdB', '+7 954 334 5796', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Rosaleen Anchor', 'ranchorf@timesonline.co.uk', 'fClxRRX52i', '+232 785 241 8989', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Eliza Greensides', 'egreensidesg@github.io', 'wFMEJY5gmy', '+420 595 611 9055', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Alick Penticoot', 'apenticooth@cocolog-nifty.com', 'NpWnzdw', '+86 320 936 3201', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Orran Gritten', 'ogritteni@livejournal.com', 'WSAErIUyOEyY', '+57 302 265 4501', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Ilise Aimson', 'iaimsonj@joomla.org', 'tvUtVO', '+48 628 671 2258', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Elwin Andreix', 'eandreixk@webmd.com', 'XBezZHmGOE', '+976 236 457 0244', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Hughie Do Rosario', 'hdol@aboutads.info', 'OsN2PTxJn5L7', '+1 360 843 2574', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Kameko Soal', 'ksoalm@google.fr', '1Ph6pjGN', '+86 119 242 4712', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Roxane Shark', 'rsharkn@issuu.com', 'lSJWfP', '+967 896 453 5343', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Hurlee Glasman', 'hglasmano@ow.ly', 's3Lf5Co3', '+351 924 573 4795', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Brandon Scutching', 'bscutchingp@state.gov', '3Wq3y5QVIZQ', '+63 131 154 3735', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Anthia Hing', 'ahingq@ycombinator.com', 'pV4I6bR', '+62 154 956 6928', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Ettie Daens', 'edaensr@purevolume.com', 'q2oi7b', '+374 804 934 4986', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Riannon Fantonetti', 'rfantonettis@state.gov', 'OV5hxlNxvNcd', '+351 721 757 8319', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Nissa Oloshkin', 'noloshkint@oracle.com', 'F3dgnJ7z', '+86 305 770 1905', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Lissy Cisar', 'lcisaru@lulu.com', 'PU9bFS8S8', '+46 982 609 6213', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Benedick Marcoolyn', 'bmarcoolynv@wired.com', 'qADz8qe', '+62 858 839 2125', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Loren Batrip', 'lbatripw@cyberchimps.com', 'IUJSfw0Xaz8', '+30 109 910 5577', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Tomlin Trow', 'ttrowx@cpanel.net', 'KjkthjW9Dx', '+86 426 729 4370', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Miranda Badam', 'mbadamy@mozilla.org', 'ykOFUNv6e', '+62 543 764 6400', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Lucais Gemelli', 'lgemelliz@hexun.com', 'KuSpVK9M', '+86 984 221 6495', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Dunn Probin', 'dprobin10@ask.com', 'wkuhGm', '+352 616 832 3863', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Kale Wandrich', 'kwandrich11@cmu.edu', 'iL3PqF', '+225 313 416 9948', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Thaddeus Rikel', 'trikel12@hugedomains.com', '7uGJV3x', '+20 348 819 5297', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Marius Vondrach', 'mvondrach13@xinhuanet.com', 'Y0DDMp', '+359 593 583 9190', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Margalo Retallick', 'mretallick14@buzzfeed.com', 'P442OPb9', '+63 791 860 4021', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Alfredo Glave', 'aglave15@stanford.edu', 'pWQV2eBh7', '+1 419 101 1257', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Lianne Ayer', 'layer16@archive.org', 'aJKV4TVI', '+86 757 984 7917', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Galvin Bertouloume', 'gbertouloume17@google.it', '2qREgbJc', '+63 338 607 9175', false);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Dieter Audas', 'daudas18@cisco.com', 'Zo5PYIkmXKU', '+7 390 355 8312', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Alard Rapinett', 'arapinett19@amazon.de', 'QBIhNZiqfqS', '+27 595 902 2614', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Melantha Oakey', 'moakey1a@amazonaws.com', 'KA6f98LcG', '+62 378 335 6278', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Shurwood Tiffin', 'stiffin1b@clickbank.net', 'FX9hbyAqkMaJ', '+353 482 295 2519', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Tracey Gniewosz', 'tgniewosz1c@shinystat.com', '0RS0OGXmT1P6', '+62 137 228 8379', true);
insert into User (FullName, Email, Password, PhoneNumber, Manager) values ('Maegan Josephov', 'mjosephov1d@ted.com', 'KaUrHz3ohau', '+86 308 977 0379', false);
